trizol/news/urls.py
__author__ = 'john'

from django.conf.urls import patterns, include, url
from django.views.generic import ListView, DetailView

from models import Entry

urlpatterns = patterns('',
    url(r'^$', ListView.as_view(queryset=Entry.objects.filter(published=True)),
        name='entry-list'),

    url(r'^(?P<slug>[\w-]+)/$', DetailView.as_view(queryset=Entry.objects.filter(published=True)),
        name='entry-detail'),

)

trizol/service/urls.py
__author__ = 'john'

from django.conf.urls import patterns, include, url
from django.views.generic import ListView, DetailView

from models import Service

urlpatterns = patterns('',
    url(r'^$', ListView.as_view(queryset=Service.objects.filter(published=True)),
        name='service-list'),

    url(r'^(?P<slug>[\w-]+)/$', DetailView.as_view(queryset=Service.objects.filter(published=True)),
        name='service-detail'),

)

trizol/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
from django.conf import settings
from django.views.generic import TemplateView
admin.autodiscover()

from trizol.views import HomeView

urlpatterns = patterns('',
    url(r'^$', HomeView.as_view(), name='home'),
    url(r'^service/', include('trizol.service.urls')),
    url(r'^works/', include('trizol.works.urls')),
    url(r'^news/', include('trizol.news.urls')),
    url(r'^about/$',TemplateView.as_view(template_name='about.html'), name='about'),
    url(r'^contacts/$',TemplateView.as_view(template_name='contacts.html'), name='contacts'),
    url(r'^admin/', include(admin.site.urls)),
)



if settings.DEBUG:
    urlpatterns = patterns('',
    url(r'^media/(?P<path>.*)$', 'django.views.static.serve',
        {'document_root': settings.MEDIA_ROOT, 'show_indexes': True}),
) + urlpatterns

trizol/works/urls.py
__author__ = 'john'

from django.conf.urls import patterns, include, url
from django.views.generic import ListView, DetailView

from models import Work

urlpatterns = patterns('',
    url(r'^$', ListView.as_view(queryset=Work.objects.filter(published=True)),
        name='work-list'),

    url(r'^(?P<slug>[\w-]+)/$', DetailView.as_view(queryset=Work.objects.filter(published=True)),
        name='work-detail'),

)

trizol/news/models.py
# -*- coding: utf-8 -*-
from django.db import models
from django.core.urlresolvers import reverse

from tinymce.models import HTMLField


class Entry(models.Model):
    title = models.CharField(max_length=80)
    slug = models.SlugField()
    description = models.TextField()
    text = HTMLField()
    image = models.ImageField(upload_to='news')
    published = models.BooleanField(default=True)
    date_added = models.DateField(auto_now_add=True)

    class Meta:
        ordering = ['-date_added', ]

    def __unicode__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("entry-detail", kwargs={'slug':self.slug})

trizol/service/models.py
# -*- coding: utf-8 -*-
from django.db import models
from django.core.urlresolvers import reverse

from tinymce.models import HTMLField


class Service(models.Model):
    title = models.CharField(max_length=80, verbose_name=u'Заголовок')
    slug = models.SlugField()
    description = models.TextField(verbose_name=u'Описание')
    text = HTMLField(verbose_name=u'Текст')
    image = models.ImageField(upload_to='service', null=True, blank=True)
    published = models.BooleanField(default=True)
    primary = models.BooleanField(default=False)

    def __unicode__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("service-detail", kwargs={'slug':self.slug})

trizol/slider/models.py
# -*- coding: utf-8 -*-
from django.db import models


class Slide(models.Model):
    name = models.CharField(max_length=50, verbose_name=u'Название')
    text = models.TextField()
    image = models.ImageField(upload_to='slider')
    published = models.BooleanField(default=True)
    position = models.IntegerField(default=0, db_index=True)

    class Meta:
        ordering = ['position',]

    def __unicode__(self):
        return self.name

trizol/works/models.py
# -*- coding: utf-8 -*-
from django.db import models
from django.core.urlresolvers import reverse

from tinymce.models import HTMLField


class Work(models.Model):
    title = models.CharField(max_length=80, verbose_name=u'Заголовок')
    slug = models.SlugField()
    text = HTMLField(verbose_name=u'Текст')
    image = models.ImageField(upload_to='works', null=True, blank=True)
    client = models.CharField(max_length=80, blank=True)
    info = models.CharField(max_length=80, blank=True)
    link = models.CharField(max_length=80, blank=True)
    date = models.DateField()
    published = models.BooleanField(default=True)

    def __unicode__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("work-detail", kwargs={'slug':self.slug})

trizol/news/views.py
# Create your views here.

trizol/service/views.py
# Create your views here.

trizol/views.py
__author__ = 'john'

from django.views.generic import TemplateView


class HomeView(TemplateView):
    template_name = 'index.html'

    def get_context_data(self, **kwargs):
        ctx = super(HomeView, self).get_context_data(**kwargs)
        return ctx

trizol/works/views.py
# Create your views here.

trizol/templates/about.html
{% extends "base.html" %}

{% load service %}

{% block meta %}
    <title>О заводе металлоконструкций Тризол</title>
    <meta name="description" content="Подробная информация о заводе металлоконструкций Тризол">
{% endblock %}


{% block main_content %}
<div class="post-13 page type-page status-publish hentry page" id="post-13">
    <div class="two_third ">
        <h2>ООО Тризол</h2>
        <p><img width="300" height="246" src="{{ STATIC_URL }}images/about.jpg" alt="" title="image_1" class="alignleft size-full wp-image-124"></p>
        <h6>Завод металлоконструкции "Тризол"</h6>
        <p>Завод основан в 2012 году.</p>
    </div>

    <div class="one_third last">
        <h2>Что мы предлагаем</h2>

        <span class="dropcap">1</span>
        <h6><em>Быстрое и качественное изготовление металлоконструкций<br></em></h6>

        <span class="dropcap">2</span>
        <h6><em>Соблюдение технических регламентов и ГОСТов при производстве<br></em></h6>

        <span class="dropcap">3</span>
        <h6><em>Выполнение и доставка заказа в соответствии с утвержденными сроками<br></em></h6>
    </div>

    <div class="clear"></div>

</div>
{% endblock %}

trizol/templates/base.html
<!DOCTYPE html>
<!--[if lt IE 7 ]><html class="ie ie6" lang="ru-RU"> <![endif]-->
<!--[if IE 7 ]><html class="ie ie7" lang="ru-RU"> <![endif]-->
<!--[if IE 8 ]><html class="ie ie8" lang="ru-RU"> <![endif]-->
<!--[if IE 9 ]><html class="ie ie9" lang="ru-RU"> <![endif]-->
<!--[if (gt IE 9)|!(IE)]><!-->
    <html class=" js flexbox rgba hsla multiplebgs backgroundsize borderimage borderradius boxshadow textshadow opacity cssanimations csscolumns cssgradients no-cssreflections csstransforms csstransforms3d csstransitions fontface generatedcontent" lang="ru-RU">
<!--<![endif]-->

<head>
<meta http-equiv="content-type" content="text/html; charset=UTF-8">
	{% block meta %}
        <title>Тризол | Металлоконструкции</title>
	    <meta name="description" content=" | Металлоконструкции">
	{% endblock %}
    <meta charset="UTF-8">
    <link rel="icon" href="{{ STATIC_URL }}images/icons/tumblr.png" type="image/x-icon">
	
    <!--[if lt IE 8]>
    <div style=' clear: both; text-align:center; position: relative;'>
    	<a href="http://www.microsoft.com/windows/internet-explorer/default.aspx?ocid=ie6_countdown_bannercode"><img src="http://storage.ie6countdown.com/assets/100/images/banners/warning_bar_0000_us.jpg" border="0" alt="" /></a>
    </div>
    <![endif]-->
    <link rel="stylesheet" type="text/css" media="all" href="{{ STATIC_URL }}css/normalize.css" />
	<link rel="stylesheet" type="text/css" media="all" href="{{ STATIC_URL }}style.css" />
    <link rel="stylesheet" type="text/css" media="all" href="{{ STATIC_URL }}css/prettyPhoto.css" />
    <link rel="stylesheet" type="text/css" media="all" href="{{ STATIC_URL }}css/grid.css" />
    <link rel="stylesheet" type="text/css" media="all" href="{{ STATIC_URL }}css/colorscheme.css" />

    <link href='http://fonts.googleapis.com/css?family=Oswald:300' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Oswald' rel='stylesheet' type='text/css'>

	
    
    <script type='text/javascript' src='{{ STATIC_URL }}js/jquery-1.7.2.min.js?ver=1.7.2'></script>
    <script type='text/javascript' src='{{ STATIC_URL }}js/modernizr.js?ver=2.0.6'></script>
    <script type='text/javascript' src='{{ STATIC_URL }}js/superfish.js?ver=1.4.8'></script>
    <script type='text/javascript' src='{{ STATIC_URL }}js/jquery.easing.1.3.js?ver=1.3'></script>
    <script type='text/javascript' src='{{ STATIC_URL }}js/jquery.prettyPhoto.js?ver=3.1.3'></script>
    <script type='text/javascript' src='{{ STATIC_URL }}js/jquery.nivo.slider.js?ver=2.5.2'></script>
    <script type='text/javascript' src='{{ STATIC_URL }}js/jquery.tools.min.js?ver=1.2.6'></script>
    <script type='text/javascript' src='{{ STATIC_URL }}js/jquery.loader.js?ver=1.0'></script>
    <script type='text/javascript' src='{{ STATIC_URL }}js/jquery.elastislide.js?ver=1.0'></script>
    <script type='text/javascript' src='{{ STATIC_URL }}js/swfobject.js?ver=2.2-20120417'></script>
    <script type='text/javascript' src='{{ STATIC_URL }}js/jquery.cycle.all.js?ver=2.99'></script>
    <script type='text/javascript' src='{{ STATIC_URL }}js/jquery.twitter.js?ver=1.0'></script>
    <script type='text/javascript' src='{{ STATIC_URL }}js/jquery.flickrush.js?ver=1.0'></script>
    <script type='text/javascript' src='{{ STATIC_URL }}js/audiojs/audio.js?ver=1.0'></script>
    <script type='text/javascript' src='{{ STATIC_URL }}js/custom.js?ver=1.0'></script>
    <script type='text/javascript' src='{{ STATIC_URL }}js/comment-reply.min.js?ver=3.5.2'></script>
    {% comment %}    
    <link rel='canonical' href='http://zmkt.ru/' />
    {% endcomment %}
    <style type="text/css" media="screen">
        html { margin-top: 28px !important; }
        * html body { margin-top: 28px !important; }
    </style>
  
  <script type="text/javascript">
  	// initialise plugins
		jQuery(function(){
			// main navigation init
			jQuery('ul.sf-menu').superfish({
				delay:       1000, 		// one second delay on mouseout
				animation:   {opacity:'show',height:'show'}, // fade-in and slide-down animation
				speed:       'normal',  // faster animation speed
				autoArrows:  false,   // generation of arrow mark-up (for submenu)
				dropShadows: false   // drop shadows (for submenu)
			});

			jQuery("ul.services li:even").addClass("even");

		});

		// Init for audiojs
		audiojs.events.ready(function() {
			var as = audiojs.createAll();
		});
  </script>

  <script type="text/javascript">
		jQuery(window).load(function() {
			// nivoslider init
			jQuery('#slider').nivoSlider({
				effect: 'fold',
				slices:15,
				boxCols:8,
				boxRows:8,
				animSpeed:500,
				pauseTime:5000,
				directionNav:false,
				directionNavHide:false,
				controlNav:true,
				captionOpacity:1,
    beforeChange: function(){
     jQuery('.nivo-caption').animate({right:"-500px"}, {easing:"jswing"});
    },
    afterChange: function(){
     jQuery('.nivo-caption').animate({right:"40"}, {easing:"jswing"});
    }
			});
		});
	</script>


  <style type="text/css">




		body {font-family:Arial, Helvetica, sans-serif; color:#333}#main {font-size:12px; font-style:normal;}  </style>
</head>

<body class="home page page-id-7 page-template page-template-page-home-php customize-support">

<div id="main"><!-- this encompasses the entire Web site -->
{% block header %}
	<header id="header">
		<div class="container_12 clearfix">
			<div class="grid_12">
                <div class="logo">
                    <a href="/" id="logo"><img src="{{ STATIC_URL }}images/logo.png" alt="Тризол" title="Металлоконструкции"></a>
                    <p class="tagline">Завод металлоконструкций</p>
                </div>

                <nav class="primary">
					<ul id="topnav" class="sf-menu sf-js-enabled">
                        <li id="menu-item-34" class="menu-item menu-item-type-post_type menu-item-object-page {% if request.path == "/" %}current-menu-item{% endif %}  page_item page-item-7 current_page_item menu-item-34"><a href="/">Главная</a></li>
                        <li id="menu-item-33" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-33 {% if "service" in request.path %}current-menu-item{% endif %}"><a href="/service/">Услуги</a></li>
                        <li id="menu-item-32" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-32 {% if "works" in request.path %}current-menu-item{% endif %}"><a href="/works/">Работы</a></li>
                        <li id="menu-item-31" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-31 {% if "about" in request.path %}current-menu-item{% endif %}"><a href="/about/">О компании</a></li>
                        <li id="menu-item-30" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-30 {% if "news" in request.path %}current-menu-item{% endif %}"><a href="/news/">Новости</a></li>
                        <li id="menu-item-29" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-29 {% if "contacts" in request.path %}current-menu-item{% endif %}"><a href="/contacts/">Контакты</a></li>
                    </ul>
                </nav>

                {% comment %}
                <div id="widget-header">
        			<div id="social_networks-2" class="widget-header">
		            	<ul class="social-networks">
			                <li>
                                <a rel="external" href="http://www.youtube.com/">
                                    <img src="{{ STATIC_URL }}images/icons/youtube.png" alt="">
                                </a>
						    </li>
							<li>
							    <a rel="external" href="https://plus.google.com/">
						    		<img src="{{ STATIC_URL }}images/icons/google.png" alt="">
								</a>
						    </li>
							<li>
							    <a rel="external" href="http://intrd.ru/feed">
						    	    <img src="{{ STATIC_URL }}images/icons/feed.png" alt="">
								</a>
						    </li>
							<li>
							    <a rel="external" href="https://www.netvibes.com/">
						    		<img src="{{ STATIC_URL }}images/icons/netvibes.png" alt="">
								</a>
						    </li>
							<li>
							    <a rel="external" href="http://twitter.com/">
						    		<img src="{{ STATIC_URL }}images/icons/twitter.png" alt="">
								</a>
						    </li>
							<li>
							    <a rel="external" href="http://www.facebook.com/">
						    	    <img src="{{ STATIC_URL }}images/icons/facebook.png" alt="">
								</a>
						    </li>
                  		</ul>
            		</div>
                </div>
                {% endcomment %}

                <form method="get" id="searchform" action="/">
                    <input name="s" value="Поиск" onblur="if(this.value=='') this.value='Поиск'" onfocus="if(this.value =='Поиск' ) this.value=''" type="text">
                    <input value="Go!" type="submit">
                </form>

            </div>
        </div>
    </header>
{% endblock %}

{% block extra_top_content %}


{% endblock %}

	<div class="primary_content_wrap">
    	<div class="primary_content_bg">
            <div class="container_12 clearfix">
                <div class="grid_12">
                    <div class="wrapper">
                        <div class="wrapper">
                        {% block main_content %}

                        {% endblock %}
                        </div>

					</div>
                </div>
            </div>
        </div>
    </div>


{% block footer_area %}


{% endblock %}



{% block footer %}
<footer id="footer">
        <div id="back-top-wrapper">
            <p id="back-top" style="display: block;">
                <a href="#top"><span></span></a>
            </p>
        </div>

		<div class="container_12 clearfix">
            <div class="grid_12">
                <div class="footer-info">
                    <div id="footer-text">
                        <a class="site-name" title="Вебстудия MEG" href="http://webmeg.ru">Вебстудия MEG</a> &copy; 2011-{% now "Y" %}
                    </div>
                </div>
			</div>
		</div>
	</footer>
{% endblock footer %}
</div>
<!-- Yandex.Metrika counter -->
<script type="text/javascript">
(function (d, w, c) {
    (w[c] = w[c] || []).push(function() {
        try {
            w.yaCounter22071292 = new Ya.Metrika({id:22071292,
                    clickmap:true,
                    trackLinks:true,
                    accurateTrackBounce:true});
        } catch(e) { }
    });

    var n = d.getElementsByTagName("script")[0],
        s = d.createElement("script"),
        f = function () { n.parentNode.insertBefore(s, n); };
    s.type = "text/javascript";
    s.async = true;
    s.src = (d.location.protocol == "https:" ? "https:" : "http:") + "//mc.yandex.ru/metrika/watch.js";

    if (w.opera == "[object Opera]") {
        d.addEventListener("DOMContentLoaded", f, false);
    } else { f(); }
})(document, window, "yandex_metrika_callbacks");
</script>
<noscript><div><img src="//mc.yandex.ru/watch/22071292" style="position:absolute; left:-9999px;" alt="" /></div></noscript>
<!-- /Yandex.Metrika counter -->

</body></html>

trizol/templates/index.html
{% extends "base.html" %}

{% load slider service thumbnail news works %}

{% block meta %}
    <title>Завод металлоконструкций</title>
    <meta name="description" content="Завод металлоконструкций Тризол предлагает услуги плазменной резки, токарные и фрезерные работы, изготовление металлоконструкций на заказ">
    <meta name='yandex-verification' content='5a0497db26dfd43a' />
{% endblock %}

{% block extra_top_content %}
<section id="slider-wrapper">
    {% get_slider as slider %}
    <div class="container_12 clearfix">
        <div class="grid_12">
            <div style="position: relative; background: url({{ slider.0.image.url }}) no-repeat scroll 0% 0% transparent;" id="slider" class="nivoSlider">
                {% for slide in slider %}
                    <img style="display: none;" src="{{ slide.image.url }}" alt="" title="#sliderCaption{{ forloop.counter }}">
                {% endfor %}


                <div class="nivo-controlNav">
                    {% for slide in slider %}
                        <a class="nivo-control {% if forloop.first %}active{% endif %}" rel="{{ forloop.counter }}">{{ forloop.counter }}</a>
                    {% endfor %}
                </div>
            </div>
            {% for slide in slider %}
            <div id="sliderCaption{{ forloop.counter }}" class="nivo-html-caption">
                <h5>{{ slide.name }}</h5>
                <p>{{ slide.text }}</p>
            </div>
            {% endfor %}
        </div>
    </div>
</section>

<div class="extra_content">
    <div class="extra_content_bg">
        <div class="container_12 clearfix">
            <div class="grid_12">
                <div id="my_cyclewidget-2">
                    <div class="title">Наши проекты</div>
                    {% get_last_works as works %}
                    <ul class="projects">
                        {% for work in works %}
                        <li>
                            <figure class="thumbnail">
                                <a href="{{ work.get_absolute_url }}" title="{{ work.title }}">
                                    {% thumbnail work.image "214x114" crop="center" as img %}
                                    <img src="{{ img.url }}" alt="{{ work.title }}">
                                    {% endthumbnail %}
                                </a>
                            </figure>
                            <strong><a href="{{ work.get_absolute_url }}">{{ work.title }}</a></strong>
                        </li>
                        {% endfor %}
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock extra_top_content %}




{% block main_content %}
<div class="grid_8 alpha">
    <div class="indent_right">
        <div class="wrapper">
            <h2>Услуги</h2>
            {% get_primary_service as service_list %}
            <ul class="recent-posts services">
                {% for service in service_list %}
                <li class="post-217 services type-services status-publish hentry {% if not forloop.counter|divisibleby:"2" %}even{% endif %}">
                    <figure class="featured-thumbnail">
                        <a title="{{ service.title }}" href="{{ service.get_absolute_url }}">
                            {% thumbnail service.image "260x120" crop="center" as img %}
                            <img src="{{ img.url }}">
                            {% endthumbnail %}
                        </a>
                    </figure>
                    <h5><a href="{{ service.get_absolute_url }}" title="{{ service.title }}">{{ service.title }}</a></h5>
                    <div class="excerpt">
                        {{ service.description }}
                    </div>
                    <div class="clear"></div>
                </li>
                {% endfor %}
            </ul>

            <a href="/service/" title="Все услуги" class="button">Все услуги</a>
        </div>
    </div>
</div>

<div class="grid_4 omega">
    <div class="wrapper">
        <div id="my_postwidget-2">
            <h2>Последние новости</h2>
            {% get_last_news as news %}
            <ul class="latestpost">
                {% for entry in news %}
                <li class="clearfix">
                    <time datetime="{{ entry.date_added|date:"c" }}">{{ entry.date_added|date:"d M" }}<span>{{ entry.date_added|date:"Y" }}</span></time>
                    <div>
                        <strong>
                            <a href="{{ entry.get_absolute_url }}" rel="bookmark" title="{{ entry.title }}">{{ entry.title }}</a>
                        </strong>
                        <div class="excerpt">
                            {{ entry.description }}
                           <a href="{{ entry.get_absolute_url }}">Подробнее</a>
                        </div>
                    </div>
                </li>
                {% endfor %}
            </ul>


            <a href="/news/" class="button">Все новости</a>

        </div>
    </div>
</div>
{% endblock %}

{% comment %}
{% block footer %}
<footer id="footer">
    <div id="back-top-wrapper">
        <p style="display: block;" id="back-top">
            <a href="#top"><span></span></a>
        </p>
    </div>

    <div class="container_12 clearfix">
        <div class="grid_12">
            <div class="footer-widget-area">
                <div class="grid_3 alpha">
                    <div id="my_twitterwidget-2">
                        <div style="display: block;" id="twitter-256363" class="twitter">
                            <h4>Twitter Feed</h4>
                            <ul style="display: block;" class="twitter_update_list">
                                <li class="firstTweet lastTweet"></li>
                            </ul>
                            <p class="preloader">Loading tweets...</p>
                        </div>
                        <script>
                            jQuery("#twitter-256363").getTwitter({
                            userName: "lorem_ipsum_dol",
                            numTweets: 2,
                            loaderText: "Loading tweets...",
                            slideIn: true,
                            showHeading: true,
                                    beforeHeading: "<h4>",
                                    afterHeading: "</h4>",
                            headingText: "Twitter Feed",
                            id:"#twitter-256363",
                            showProfileLink: false
                            });
                        </script>

                    </div>
                </div>

                <div class="grid_3">
                    <div id="social_networks-3">
                        <h4>Follow us</h4>
                        <ul class="social-networks">
                            <li>
                                <a rel="external" href="http://www.youtube.com/">
                                    <img src="trizol_files/youtube.png" alt="">
                                    Watch us on Youtube
                                </a>
                            </li>
                            <li>
                                <a rel="external" href="http://intrd.ru/feed">
                                    <img src="trizol_files/feed.png" alt="">
                                    RSS Feed
                                </a>
                            </li>
                            <li>
                                <a rel="external" href="http://twitter.com/">
                                    <img src="trizol_files/twitter.png" alt="">
                                    Follow us on Twitter
                                </a>
                            </li>
                            <li>
                                <a rel="external" href="http://www.facebook.com/">
                                    <img src="trizol_files/facebook.png" alt="">
                                    Be a fan on Facebook
                                </a>
                            </li>
                        </ul>
                    </div>
                </div>

                <div class="grid_3">
                    <div id="flickr-photostream"><h4>Photostream</h4><div id="photoAlbum">
                <span class="flickrImage">
                    <a href="http://www.flickr.com/photos/54088809@N05/5197442995/"><img alt="photo" src="trizol_files/5197442995_e5fc3488d6_s.jpg" title=""></a>
                </span>
                <span class="flickrImage">
                    <a href="http://www.flickr.com/photos/54088809@N05/5198040068/"><img alt="photo" src="trizol_files/5198040068_487e0cb383_s.jpg" title=""></a>
                </span>
                <span class="flickrImage">
                    <a href="http://www.flickr.com/photos/54088809@N05/5197444145/"><img alt="photo" src="trizol_files/5197444145_3cab7093ed_s.jpg" title=""></a>
                </span>
                <span class="flickrImage">
                    <a href="http://www.flickr.com/photos/54088809@N05/5198041410/"><img alt="photo" src="trizol_files/5198041410_4abaed8413_s.jpg" title=""></a>
                </span>
                <span class="flickrImage">
                    <a href="http://www.flickr.com/photos/54088809@N05/5197443345/"><img alt="photo" src="trizol_files/5197443345_e666afb378_s.jpg" title=""></a>
                </span>
                <span class="flickrImage">
                    <a href="http://www.flickr.com/photos/54088809@N05/5140157338/"><img alt="photo" src="trizol_files/5140157338_2432083f4c_s.jpg" title=""></a>
                </span>
                <span class="flickrImage">
                    <a href="http://www.flickr.com/photos/54088809@N05/5197441813/"><img alt="photo" src="trizol_files/5197441813_54cf29ed0a_s.jpg" title=""></a>
                </span><div class="more"><a href="http://www.flickr.com/photos/54088809@N05">View More</a></div></div></div>                        </div>

                <div class="grid_3 omega">
                    <div id="text-3"><h4>Quick Contact</h4>			<div class="textwidget"><div class="wpcf7" id="wpcf7-f41-w1-o1"><form action="/#wpcf7-f41-w1-o1" method="post" class="wpcf7-form" novalidate="novalidate">
<div style="display: none;">
<input name="_wpcf7" value="41" type="hidden">
<input name="_wpcf7_version" value="3.4.2" type="hidden">
<input name="_wpcf7_unit_tag" value="wpcf7-f41-w1-o1" type="hidden">
<input name="_wpnonce" value="be705fcfeb" type="hidden">
</div>
<p><span class="wpcf7-form-control-wrap text-462"><input name="text-462" size="40" class="wpcf7-form-control wpcf7-text wpcf7-validates-as-required" aria-required="true" placeholder="Имя*" type="text"></span></p>
<p><span class="wpcf7-form-control-wrap email-613"><input name="email-613" size="40" class="wpcf7-form-control wpcf7-text wpcf7-email wpcf7-validates-as-required wpcf7-validates-as-email" aria-required="true" placeholder="E-mail*" type="email"></span></p>
<p><span class="wpcf7-form-control-wrap textarea-172"><textarea name="textarea-172" cols="40" rows="10" class="wpcf7-form-control wpcf7-textarea" placeholder="Сообщение"></textarea></span></p>
<p><input value="Отправить" class="wpcf7-form-control wpcf7-submit" type="submit"><img style="visibility: hidden;" alt="Отправка..." src="trizol_files/ajax-loader.gif" class="ajax-loader"></p>
<div class="wpcf7-response-output wpcf7-display-none"></div></form></div></div>
</div>                        </div>

            </div>






        <div class="footer-info">

            <div id="footer-text">
            <a class="site-name" title="Металлоконструкции" href="/">Тризол</a> &copy; 2011-{% now "Y" %}
            </div>


        </div>




    </div>
</div><!--.container-->
</footer>
{% endblock %}
{% endcomment %}